//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace huy
{
    using System;
    using System.Collections.Generic;
    
    public partial class tovar
    {
        public string art { get; set; }
        public string name { get; set; }
        public string ed_ism { get; set; }
        public int price { get; set; }
        public double max_sale { get; set; }
        public string proisvod { get; set; }
        public string post { get; set; }
        public int kat_tov { get; set; }
        public double sale { get; set; }
        public int colvo { get; set; }
        public string opis { get; set; }
        public string img { get; set; }
    }
}
